from pyspark.sql import SparkSession, functions as F
spark = SparkSession.builder.master("local[2]").appName("Check2026Q1").getOrCreate()
spark.sparkContext.setLogLevel("ERROR")
df = spark.read.parquet("/user/jl17797_nyu_edu/oss_pulse/cleaned/gharchive_2026q1/event_date=2026-01-15")
print("=== columns ===")
print(df.columns)
pr = df.filter(F.col("event_type")=="PullRequestEvent")
print(f"\n=== PR events: {pr.count()} ===")
pr.select("pr_merged","payload_action","pr_number").show(10, False)
print("=== pr_merged value counts ===")
pr.groupBy("pr_merged").count().show()
print("=== payload_action value counts ===")
pr.groupBy("payload_action").count().show()
print("=== push_distinct_size sample ===")
df.filter(F.col("event_type")=="PushEvent").select("push_distinct_size").show(5)
spark.stop()
